ICDC_Portal/Controllers/UserAccountDetailsController.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ICDC_Portal.OData;

namespace ICDC_Portal.Controllers
{
    public class UserAccountDetailsController : Controller
    {
        public NAV Nav = new NAV(new Uri(ConfigurationManager.AppSettings["ODATA_URI"]))
        {
            Credentials =
          new NetworkCredential(ConfigurationManager.AppSettings["W_USER"],
              ConfigurationManager.AppSettings["W_PWD"], ConfigurationManager.AppSettings["DOMAIN"])
        };
        // GET: UserAccountDetails
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult GetUserDetails()
        {
            var listform = Nav.applicantsRegister.Where(r => r.Username == Session["username"].ToString()).ToList();

            return View(listform);
        }
    }
}

ICDC_Portal/Controllers/UserRegistrationController.cs
using System;
using System.Configuration;
using System.Data;
using System.Data.SqlClient;
using System.Net;
using System.Linq;
using System.Net.Mail;
using System.Security.Cryptography;
using System.Text;
using System.Web.Mvc;
using ICDC_Portal.Models;
using ICDC_Portal.OData;
using ICDC_Portal.WSRAPI;

namespace ICDC_Portal.Controllers
{
   
    public class UserRegistrationController : Controller
    {
        public NAV Nav = new NAV(new Uri(ConfigurationManager.AppSettings["ODATA_URI"]))
        {
            Credentials =
           new NetworkCredential(ConfigurationManager.AppSettings["W_USER"],
               ConfigurationManager.AppSettings["W_PWD"], ConfigurationManager.AppSettings["DOMAIN"])
        };

        public static readonly string StrSqlConn = @"Server=" + ConfigurationManager.AppSettings["DB_INSTANCE"] + ";Database=" +
                                  ConfigurationManager.AppSettings["DB_NAME"] + "; User ID=" +
                                  ConfigurationManager.AppSettings["DB_USER"] + "; Password=" +
                                  ConfigurationManager.AppSettings["DB_PWD"] + "; MultipleActiveResultSets=true";

        public string CompanyName = "ICDC";
        // GET: User_Registration
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult SaveUserAccountDetails(){

            return View();
        }
        [HttpPost]
        //public JsonResult SaveUserAccountDetails(DetailsInsertClass regUser)
        //{
        //    bool status = InsertData(regUser);

        //    return new JsonResult { Data = status };
        //}

        public ActionResult SaveUserAccountDetails(DetailsInsertClass regUser)
        {
            bool status = InsertData(regUser);
            switch (status)
            {
                case true:
                    TempData["Success"] = "Your Account Successfully created, Go to your EMAIL to activate";
                    ViewBag.Message = "Your Account Successfully created, Go to your EMAIL to activate";
                    break;
                case false:
                    TempData["Failed"] = "Failed to create Account, try again later!";
                    ViewBag.Message= "Failed to create Account, try again later!";
                    break;
            }
           // return View("SaveUserAccountDetails");
            return RedirectToAction("SaveUserAccountDetails");
        }

        protected bool InsertData(DetailsInsertClass regUser)
        {
            bool datasaved = false;
            try
            {
                var credentials = new NetworkCredential(ConfigurationManager.AppSettings["W_USER"], ConfigurationManager.AppSettings["W_PWD"], ConfigurationManager.AppSettings["DOMAIN"]);
                WebPortal webp = new WebPortal();
                webp.Credentials = credentials;
                webp.PreAuthenticate = true;
                if (webp.FnCreateApplicants(regUser.FirstName, regUser.MiddleName, regUser.LastName, regUser.UserName,regUser.Email, EncryptP(regUser.Password2), regUser.ActivationCode.ToString()))
                {
                    //  this.Page.ClientScript.RegisterStartupScript(this.GetType(), "alert", "getmeTohomeConfirm()", true);

                    //call goback to login to load Default page for user

                    InsertToActivationDb(regUser.UserName, regUser.ActivationCode.ToString());

                    using (MailMessage mm = new MailMessage("ngutumbuvi8@gmail.com", regUser.Email))
                    {
                        
                        mm.Subject = "ICDC Account Activation";
                        string body = "Hello " + regUser.UserName + ",";
                        body += "<br /><br />Please click the following link to activate your account";
                        if (Request.Url != null)
                            body += "<br /><a href = '" + string.Format("{0}://{1}/UserRegistration/ActivateMyAccount/{2}", Request.Url.Scheme, Request.Url.Authority, regUser.ActivationCode) + "'>Click here to activate your account.</a>";
                        body += "<br /><br />Thanks";
                        mm.Body = body;
                        mm.IsBodyHtml = true;

                        //when no proxy used
                        SmtpClient smtp = new SmtpClient();


                        //string smtpAddress = "smtp.mail.yahoo.com";
                        //int portNumber = 587;
                        //bool enableSSL = true;



                        smtp.Host = "smtp.gmail.com";
                        smtp.EnableSsl = true;
                        NetworkCredential networkCred = new NetworkCredential("ngutumbuvi8@gmail.com", "ngutu12345");
                        smtp.UseDefaultCredentials = true;
                        smtp.Credentials = networkCred;
                        smtp.Port = 587;
                        smtp.Send(mm);
                        
                    }
                    datasaved = true;
                }
                else
                {
                    datasaved = false;
                }
        }
            catch (Exception ex)
            {
                // ignored
            }
            return datasaved;
        }

        static string EncryptP(string mypass)
        {
            //encryptpassword:
            using (MD5CryptoServiceProvider md5 = new MD5CryptoServiceProvider())
            {
                UTF8Encoding utf8 = new UTF8Encoding();
                byte[] data = md5.ComputeHash(utf8.GetBytes(mypass));
                return Convert.ToBase64String(data);
            }
        }

        public ActionResult EditProfile()
        {
            return View();
        }

        public ActionResult ActivateMyAccount()
        {
            try
            {
                
                if (RouteData.Values["id"] != null)
                {
                    Guid activationCode = new Guid(RouteData.Values["id"].ToString());
                    ActivatedfromDb(activationCode);
                }
                
            }
            catch (Exception ex)
            {
                // ignored
            }
            return View();
        }

        public void ActivatedfromDb(Guid actiVCode)
        {
            var credentials = new NetworkCredential(ConfigurationManager.AppSettings["W_USER"], ConfigurationManager.AppSettings["W_PWD"], ConfigurationManager.AppSettings["DOMAIN"]);
            WebPortal webp = new WebPortal();
            webp.Credentials = credentials;
            webp.PreAuthenticate = true;

            var activatem = Nav.applicantsRegister.ToList().Where(r => r.Activation_Code == actiVCode.ToString());
            string activatemyAss = activatem.Select(r => r.Activation_Code).SingleOrDefault();
            using (SqlConnection con = new SqlConnection(StrSqlConn))
            {
                using (SqlCommand cmd = new SqlCommand("DELETE FROM UserActivation WHERE ActivationCode = @ActivationCode"))
                {
                    using (SqlDataAdapter sda = new SqlDataAdapter())
                    {
                        cmd.CommandType = CommandType.Text;
                        cmd.Parameters.AddWithValue("@ActivationCode", actiVCode);
                        cmd.Connection = con;
                        con.Open();
                        int rowsAffected = cmd.ExecuteNonQuery();
                        con.Close();
                        if (rowsAffected == 1)
                        {
                            bool status = webp.FnActivateAc(activatemyAss);
                            switch (status)
                            {
                                case true:
                                    //successful activation
                                    TempData["green"] = "Your Account Activated Successfully";
                                    break;
                                //failed activation
                                case false:
                                    TempData["red"] = "Failed to activate account";
                                    break;
                            }
                           
                        }
                        else
                        {
                            //failed activation
                            TempData["red"] = "Account Already active!";
                        }
                    }
                }
            }
        }
        public void InsertToActivationDb(string userName, string actvCode)
        {
            using (SqlConnection con = new SqlConnection(StrSqlConn))
            {
                using (SqlCommand cmd = new SqlCommand("INSERT INTO UserActivation VALUES(@UserId, @ActivationCode)"))
                {
                    using (SqlDataAdapter sda = new SqlDataAdapter())
                    {
                        cmd.CommandType = CommandType.Text;
                        cmd.Parameters.AddWithValue("@UserId", userName);
                        cmd.Parameters.AddWithValue("@ActivationCode", actvCode);
                        cmd.Connection = con;
                        con.Open();
                        cmd.ExecuteNonQuery();
                        con.Close();
                    }
                }
            }
        }
    }
}

ICDC_Portal/Views/Shared/View.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>@ViewBag.Title - ICDC Project</title>

    <!-- Bootstrap Core CSS -->
    <link href="/Content/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <!-- MetisMenu CSS -->
    <link href="/Content/vendor/metisMenu/metisMenu.min.css" rel="stylesheet">
    <!-- Custom CSS -->
    <link href="/Content/dist/css/sb-admin-2.css" rel="stylesheet">
    <!-- Morris Charts CSS -->
    <link href="/Content/vendor/morrisjs/morris.css" rel="stylesheet">
    <!-- Custom Fonts -->
    <link href="/Content/vendor/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">

    <link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet"/>

    @*custom CSS ref*@
    <link href="/Content/Site.css" rel="stylesheet">

</head>
<body>

<!-- Navigation -->
<nav class="navbar navbar-default navbar-fixed-top" role="navigation" style="margin-bottom: 0">
<div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle Nav</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
    </button>
    @Html.ActionLink("ICDC Project", "Index", "Home", new {area = ""}, new {@class = "navbar-brand"})
</div>
<!-- /.navbar-header -->
<ul class="nav navbar-top-links navbar-right">
    <li class="dropdown">
        <a class="dropdown-toggle" data-toggle="dropdown" href="#">
            <i class="fa fa-envelope fa-fw"></i> <i class="fa fa-caret-down"></i>
        </a>
        <ul class="dropdown-menu dropdown-messages">
            <li>
                <a href="#">
                    <div>
                        <strong>Steph Curry</strong>
                        <span class="pull-right text-muted">
                                    <em>Yesterday</em>
                                </span>
                    </div>
                    <div>tested today...</div>
                </a>
            </li>
            <li class="divider"></li>
            <li>
                <a href="#">
                    <div>
                        <strong>Sean Andre</strong>
                        <span class="pull-right text-muted">
                                    <em>Yesterday</em>
                                </span>
                    </div>
                    <div>tested yesterday...</div>
                </a>
            </li>

        </ul>
        <!-- /.dropdown-messages -->
    </li>
    <!-- /.dropdown -->
    <li class="dropdown">
        <a class="dropdown-toggle" data-toggle="dropdown" href="#">
            <i class="fa fa-tasks fa-fw"></i> <i class="fa fa-caret-down"></i>
        </a>
        <ul class="dropdown-menu dropdown-tasks">
            <li>
                <a href="#">
                    <div>
                        <p>
                            <strong>Task 1</strong>
                            <span class="pull-right text-muted">40% Complete</span>
                        </p>
                        <div class="progress progress-striped active">
                            <div class="progress-bar progress-bar-success" role="progressbar" aria-valuenow="40" aria-valuemin="0" aria-valuemax="100" style="width: 40%">
                                <span class="sr-only">40% Complete (success)</span>
                            </div>
                        </div>
                    </div>
                </a>
            </li>
            <li class="divider"></li>
            <li>
                <a href="#">
                    <div>
                        <p>
                            <strong>Second Task </strong>
                            <span class="pull-right text-muted">20% Complete</span>
                        </p>
                        <div class="progress progress-striped active">
                            <div class="progress-bar progress-bar-info" role="progressbar" aria-valuenow="20" aria-valuemin="0" aria-valuemax="100" style="width: 20%">
                                <span class="sr-only">20% Complete</span>
                            </div>
                        </div>
                    </div>
                </a>
            </li>

        </ul>
        <!-- /.dropdown-tasks -->
    </li>
    <!-- /.dropdown -->
    <li class="dropdown">
        <a class="dropdown-toggle" data-toggle="dropdown" href="#">
            <i class="fa fa-bell fa-fw"></i> <i class="fa fa-caret-down"></i>
        </a>
        <ul class="dropdown-menu dropdown-alerts">
            <li>
                <a href="#">
                    <div>
                        <i class="fa fa-comment fa-fw"></i> New Comment
                        <span class="pull-right text-muted small">4 minutes ago</span>
                    </div>
                </a>
            </li>
            <li class="divider"></li>
            <li>
                <a href="#">
                    <div>
                        <i class="fa fa-twitter fa-fw"></i> 3 New Followers
                        <span class="pull-right text-muted small">12 minutes ago</span>
                    </div>
                </a>
            </li>

        </ul>
        <!-- /.dropdown-alerts -->
    </li>
    <!-- /.dropdown -->
    <li class="dropdown">
        <a class="dropdown-toggle" data-toggle="dropdown" href="#">
            <i class="fa fa-user-circle" aria-hidden="true"></i> <span>@Session["username"].ToString()</span> <i class="fa fa-caret-down"></i>
        </a>
        <ul class="dropdown-menu dropdown-user">
            <li>
                <a href="#"><i class="fa fa-user-circle" aria-hidden="true"></i> My Profile</a>
            </li>
            <li>
                <a href="#"><i class="fa fa-gear fa-fw"></i> Settings</a>
            </li>
            <li> <a href="@Url.Action("SaveUserAccountDetails", "Home")">Create CV</a></li>
            <li class="divider"></li>
            <li>
                <a href="#"><i class="fa fa-sign-out fa-fw"></i> Logout</a>
            </li>
        </ul>
        <!-- /.dropdown-user -->
    </li>
    <!-- /.dropdown -->
</ul>
<!-- /.navbar-top-links -->
<div class="navbar-default sidebar" role="navigation">
    <div class="sidebar-nav navbar-collapse">
        <ul class="nav" id="side-menu">
            <li class="sidebar-search">
                <div class="input-group custom-search-form">
                    <input type="text" class="form-control" placeholder="Search...">
                    <span class="input-group-btn">
                                <button class="btn btn-default" type="button">
                                    <i class="fa fa-search"></i>
                                </button>
                            </span>
                </div>
                <!-- /input-group -->
            </li>
            <li>
                <a href="#"><i class="fa fa-dashboard fa-fw"></i> Dashboard</a>
            </li>
            <li>
                <a href="#"><i class="fa fa-bar-chart-o fa-fw"></i> Charts<span class="fa arrow"></span></a>
                <ul class="nav nav-second-level">
                    <li>
                        <a href="#">Flot Charts</a>
                    </li>
                    <li>
                        <a href="#">Morris.js Charts</a>
                    </li>
                </ul>
                <!-- /.nav-second-level -->
            </li>
            <li>
                <a href="tables.html"><i class="fa fa-table fa-fw"></i> Tables</a>
            </li>
            <li>
                <a href="forms.html"><i class="fa fa-edit fa-fw"></i> Forms</a>
            </li>
            <li>
                <a href="#"><i class="fa fa-wrench fa-fw"></i> UI Elements<span class="fa arrow"></span></a>
                <ul class="nav nav-second-level">
                    <li>
                        <a href="panels-wells.html">Panels and Wells</a>
                    </li>
                    <li>
                        <a href="buttons.html">Buttons</a>
                    </li>
                    <li>
                        <a href="notifications.html">Notifications</a>
                    </li>
                    <li>
                        <a href="typography.html">Typography</a>
                    </li>
                    <li>
                        <a href="icons.html"> Icons</a>
                    </li>
                    <li>
                        <a href="grid.html">Grid</a>
                    </li>
                </ul>
                <!-- /.nav-second-level -->
            </li>
            <li>
                <a href="#"><i class="fa fa-files-o fa-fw"></i> Sample Pages<span class="fa arrow"></span></a>
                <ul class="nav nav-second-level">
                    <li>
                        <a href="blank.html">Blank Page</a>
                    </li>
                    <li>
                        <a href="login.html">Login Page</a>
                    </li>
                </ul>
                <!-- /.nav-second-level -->
            </li>
        </ul>
    </div>
    <!-- /.sidebar-collapse -->
</div>
<!-- /.navbar-static-side -->
</nav>

@RenderBody()<hr/>
<footer class="footer">
    <p>&copy; @DateTime.Now.Year - Surestep Systems & Solutions</p>
</footer>



<!-- jQuery -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
@*<script src="/Content/vendor/jquery/jquery.min.js"></script>*@
<!-- Bootstrap Core JavaScript -->
<script src="/Content/vendor/bootstrap/js/bootstrap.min.js"></script>
<!-- Metis Menu Plugin JavaScript -->
<script src="/Content/vendor/metisMenu/metisMenu.min.js"></script>
<!-- Morris Charts JavaScript -->
<script src="/Content/vendor/raphael/raphael.min.js"></script>
<script src="/Content/vendor/morrisjs/morris.min.js"></script>
<script src="/Content/dist/js/morris-data.js"></script>
<!-- Custom Theme JavaScript -->
<script src="/Content/dist/js/sb-admin-2.js"></script>

<!-- DataTables JavaScript -->
<script src="/Content/vendor/datatables/js/jquery.dataTables.min.js"></script>
<script src="/Content/vendor/datatables-plugins/dataTables.bootstrap.min.js"></script>
<script src="/Content/vendor/datatables-responsive/dataTables.responsive.js"></script>
<script src="/Scripts/vue.min.js"></script>
</body>
</html>



@*User information displayed here*@
<div class="row">
    <div class="col-lg-4">
        <div class="panel panel-default">
            <div class="panel-heading"> My profile Information</div>
            <!-- /.panel-heading -->
            <div class="panel-body">

            </div>
            <!-- /.panel-body -->
        </div>
    </div>

    <div class="col-lg-8">
        <div class="panel panel-default">
            <div class="panel-heading"> Basic Information</div>
            <!-- /.panel-heading -->
            <div>
                @Html.Action("GetUserDetails", "UserAccountDetails")
            </div>
            <!-- /.panel-body -->
            <i class="fa-pencil-square-o">
                <a href="@Url.Action("EditProfile", "UserRegistration")">Edit Profile</a>
            </i>
        </div>
    </div>

</div>

ICDC_Portal/Views/Shared/_General_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>@ViewBag.Title - ICDC Project</title>

    <!-- Bootstrap Core CSS -->
    <link href="/Content/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <!-- MetisMenu CSS -->
    <link href="/Content/vendor/metisMenu/metisMenu.min.css" rel="stylesheet">
    <!-- Custom CSS -->
    <link href="/Content/dist/css/sb-admin-2.css" rel="stylesheet">
    <!-- Morris Charts CSS -->
    <link href="/Content/vendor/morrisjs/morris.css" rel="stylesheet">
    <!-- Custom Fonts -->
    <link href="/Content/vendor/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">

    <link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet"/>

    <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>

    <script type="text/javascript" src="http://ajax.cdnjs.com/ajax/libs/json2/20110223/json2.js"></script>

    @*custom CSS ref*@
    <link href="/Content/Site.css" rel="stylesheet">

</head>
<body>

    <!-- Navigation -->
<nav class="navbar navbar-default navbar-fixed-top" role="navigation" style="margin-bottom: 0">
    <div class="navbar-header">
        <a href="@Url.Action("SignIn", "Login")"><img src="/siteimages/favicon.ico" style="max-height: 80px"/></a>
    </div>
</nav>
<br/>
    <br/>
    @RenderBody() <hr />
       
    <footer class="footer">
        <p>&copy; @DateTime.Now.Year - Surestep Systems & Solutions</p>
    </footer>


    <!-- jQuery -->
        @*<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>*@
    <!-- Bootstrap Core JavaScript -->
    <script src="/Content/vendor/jquery/jquery.min.js"></script>

    <script src="/Content/vendor/bootstrap/js/bootstrap.min.js"></script>
    <!-- Metis Menu Plugin JavaScript -->
    <script src="/Content/vendor/metisMenu/metisMenu.min.js"></script>
    <!-- Morris Charts JavaScript -->
    <script src="/Content/vendor/raphael/raphael.min.js"></script>
    <script src="/Content/vendor/morrisjs/morris.min.js"></script>
    <script src="/Content/dist/js/morris-data.js"></script>
    <!-- Custom Theme JavaScript -->
    <script src="/Content/dist/js/sb-admin-2.js"></script>

    <!-- DataTables JavaScript -->
    <script src="/Content/vendor/datatables/js/jquery.dataTables.min.js"></script>
    <script src="/Content/vendor/datatables-plugins/dataTables.bootstrap.min.js"></script>
    <script src="/Content/vendor/datatables-responsive/dataTables.responsive.js"></script>
    <script src="/Scripts/vue.min.js"></script>
</body>
</html>

ICDC_Portal/Views/Shared/_Login_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>@ViewBag.Title - ICDC Project</title>

    <!-- Bootstrap Core CSS -->
    <link href="/Content/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <!-- MetisMenu CSS -->
    <link href="/Content/vendor/metisMenu/metisMenu.min.css" rel="stylesheet">
    <!-- Custom CSS -->
    <link href="/Content/dist/css/sb-admin-2.css" rel="stylesheet">
    <!-- Morris Charts CSS -->
    <link href="/Content/vendor/morrisjs/morris.css" rel="stylesheet">
    <!-- Custom Fonts -->
    <link href="/Content/vendor/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">

    <link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" />

    <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>

    <script type="text/javascript" src="http://ajax.cdnjs.com/ajax/libs/json2/20110223/json2.js"></script>

    @*custom CSS ref*@
    <link href="/Content/Site.css" rel="stylesheet">

</head>
<body>
  
    @RenderBody() <hr />

    <footer class="footer">
        <p>&copy; @DateTime.Now.Year - Surestep Systems & Solutions</p>
    </footer>


    <!-- jQuery -->
    @*<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>*@
    <!-- Bootstrap Core JavaScript -->
    <script src="/Content/vendor/jquery/jquery.min.js"></script>

    <script src="/Content/vendor/bootstrap/js/bootstrap.min.js"></script>
    <!-- Metis Menu Plugin JavaScript -->
    <script src="/Content/vendor/metisMenu/metisMenu.min.js"></script>
    <!-- Morris Charts JavaScript -->
    <script src="/Content/vendor/raphael/raphael.min.js"></script>
    <script src="/Content/vendor/morrisjs/morris.min.js"></script>
    <script src="/Content/dist/js/morris-data.js"></script>
    <!-- Custom Theme JavaScript -->
    <script src="/Content/dist/js/sb-admin-2.js"></script>

    <!-- DataTables JavaScript -->
    <script src="/Content/vendor/datatables/js/jquery.dataTables.min.js"></script>
    <script src="/Content/vendor/datatables-plugins/dataTables.bootstrap.min.js"></script>
    <script src="/Content/vendor/datatables-responsive/dataTables.responsive.js"></script>
    <script src="/Scripts/vue.min.js"></script>
</body>
</html>